-- vim.g.indent_blankline_background_highlight = ""
-- vim.g.indent_blankline_use_treesitter = true
-- vim.g.indent_blankline_show_trailing_blankline_indent = false
-- vim.g.indent_blankline_show_end_of_line = true
-- vim.g.indent_blankline_filetype_exclude = { 'NvimTree', 'startify', 'dashboard' }
--
-- local highlight = {
--     "Whitespace",
-- }
-- require("ibl").setup {
--     indent = { highlight = highlight, char = "" },
--     whitespace = {
--         highlight = highlight,
--         remove_blankline_trail = false,
--     },
--     scope = { enabled = false },
-- }
